pipeline {
    agent none
  environment {
       DOCKER_TOKEN = credentials('jjdocker')
   }
  stages {
        stage('Build and Push Venafi App Images ') {
            agent {
                kubernetes {
                    cloud 'kubernetes'
                    label 'kubeagent'
                    defaultContainer 'docker-agent'
                }
            }
            steps {
                script {
                    sh 'pwd'
                    sh 'docker login -u=jeveenj -p=$DOCKER_TOKEN && docker compose -f venafi-docker-compose.yaml build && docker compose -f venafi-docker-compose.yaml push'
                    
                }
            }
        }
    stage('Venafi Script Container Deployment') {
     agent {
            kubernetes {
                cloud 'kubernetes'
                label 'kubeagent'
                defaultContainer 'jnlp'
              }
           }
      steps {
               echo "Automation script execution started"
               sh(
                  script:
                         """\
                        kubectl apply -f ./venafi/venafi_deployment.yaml
                         """,
                      )
                echo "Automation script execution done"      
            }
        }
    }
}
