pipeline {
    agent none
  stages {
    stage('Venafi Script Container Deployment') {
     agent {
            kubernetes {
                cloud 'kubernetes'
                label 'kubeagent'
                defaultContainer 'jnlp'
              }
           }
      steps {
               echo "Automation script execution started"
               sh(
                  script:
                         """\
                        kubectl apply -f ./venafi/venafi_deployment.yaml
                         """,
                      )
                echo "Automation script execution done"      
            }
        }
    }
}
